// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: apis/v1/errors.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on ApiErrorResponse with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *ApiErrorResponse) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetError()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ApiErrorResponseValidationError{
				field:  "Error",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// ApiErrorResponseValidationError is the validation error returned by
// ApiErrorResponse.Validate if the designated constraints aren't met.
type ApiErrorResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ApiErrorResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ApiErrorResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ApiErrorResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ApiErrorResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ApiErrorResponseValidationError) ErrorName() string { return "ApiErrorResponseValidationError" }

// Error satisfies the builtin error interface
func (e ApiErrorResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sApiErrorResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ApiErrorResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ApiErrorResponseValidationError{}

// Validate checks the field values on ApiError with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *ApiError) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Code

	// no validation rules for Message

	// no validation rules for Type

	// no validation rules for TraceId

	if v, ok := interface{}(m.GetDetails()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ApiErrorValidationError{
				field:  "Details",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// ApiErrorValidationError is the validation error returned by
// ApiError.Validate if the designated constraints aren't met.
type ApiErrorValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ApiErrorValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ApiErrorValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ApiErrorValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ApiErrorValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ApiErrorValidationError) ErrorName() string { return "ApiErrorValidationError" }

// Error satisfies the builtin error interface
func (e ApiErrorValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sApiError.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ApiErrorValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ApiErrorValidationError{}
