// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        (unknown)
// source: apis/v1/errors.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorCode
type ErrorCode int32

const (
	// Default
	ErrorCode_ERROR_CODE_INVALID ErrorCode = 0
	// Unauthorized request
	ErrorCode_UNAUTHORIZED ErrorCode = 1
	// Bad request. Input parameters are malformed
	ErrorCode_BAD_REQUEST      ErrorCode = 2
	ErrorCode_NOT_FOUND        ErrorCode = 4
	ErrorCode_EMAIL_UNVERIFIED ErrorCode = 5
	ErrorCode_UNKNOWN          ErrorCode = 1000
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:    "ERROR_CODE_INVALID",
		1:    "UNAUTHORIZED",
		2:    "BAD_REQUEST",
		4:    "NOT_FOUND",
		5:    "EMAIL_UNVERIFIED",
		1000: "UNKNOWN",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_INVALID": 0,
		"UNAUTHORIZED":       1,
		"BAD_REQUEST":        2,
		"NOT_FOUND":          4,
		"EMAIL_UNVERIFIED":   5,
		"UNKNOWN":            1000,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_apis_v1_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_apis_v1_errors_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_apis_v1_errors_proto_rawDescGZIP(), []int{0}
}

type ApiErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *ApiError `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ApiErrorResponse) Reset() {
	*x = ApiErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_v1_errors_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiErrorResponse) ProtoMessage() {}

func (x *ApiErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_v1_errors_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiErrorResponse.ProtoReflect.Descriptor instead.
func (*ApiErrorResponse) Descriptor() ([]byte, []int) {
	return file_apis_v1_errors_proto_rawDescGZIP(), []int{0}
}

func (x *ApiErrorResponse) GetError() *ApiError {
	if x != nil {
		return x.Error
	}
	return nil
}

type ApiError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Type of error.
	Code ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=apis.v1.ErrorCode" json:"code,omitempty"`
	// Detail message of error
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Type of error. In plain text.
	Type    string           `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	TraceId string           `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Details *structpb.Struct `protobuf:"bytes,5,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *ApiError) Reset() {
	*x = ApiError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_v1_errors_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiError) ProtoMessage() {}

func (x *ApiError) ProtoReflect() protoreflect.Message {
	mi := &file_apis_v1_errors_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiError.ProtoReflect.Descriptor instead.
func (*ApiError) Descriptor() ([]byte, []int) {
	return file_apis_v1_errors_proto_rawDescGZIP(), []int{1}
}

func (x *ApiError) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_INVALID
}

func (x *ApiError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiError) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ApiError) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ApiError) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_apis_v1_errors_proto protoreflect.FileDescriptor

var file_apis_v1_errors_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b, 0x0a,
	0x10, 0x41, 0x70, 0x69, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x27, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x70, 0x69, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xae, 0x01, 0x0a, 0x08, 0x41,
	0x70, 0x69, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x26, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x31, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x2a, 0x79, 0x0a, 0x09, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00,
	0x12, 0x10, 0x0a, 0x0c, 0x55, 0x4e, 0x41, 0x55, 0x54, 0x48, 0x4f, 0x52, 0x49, 0x5a, 0x45, 0x44,
	0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x41, 0x44, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53,
	0x54, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44,
	0x10, 0x04, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x4d, 0x41, 0x49, 0x4c, 0x5f, 0x55, 0x4e, 0x56, 0x45,
	0x52, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x05, 0x12, 0x0c, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0xe8, 0x07, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x66, 0x61, 0x35, 0x35, 0x39, 0x32, 0x32, 0x32, 0x30, 0x2f,
	0x61, 0x70, 0x69, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apis_v1_errors_proto_rawDescOnce sync.Once
	file_apis_v1_errors_proto_rawDescData = file_apis_v1_errors_proto_rawDesc
)

func file_apis_v1_errors_proto_rawDescGZIP() []byte {
	file_apis_v1_errors_proto_rawDescOnce.Do(func() {
		file_apis_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(file_apis_v1_errors_proto_rawDescData)
	})
	return file_apis_v1_errors_proto_rawDescData
}

var file_apis_v1_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_apis_v1_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_apis_v1_errors_proto_goTypes = []interface{}{
	(ErrorCode)(0),           // 0: apis.v1.ErrorCode
	(*ApiErrorResponse)(nil), // 1: apis.v1.ApiErrorResponse
	(*ApiError)(nil),         // 2: apis.v1.ApiError
	(*structpb.Struct)(nil),  // 3: google.protobuf.Struct
}
var file_apis_v1_errors_proto_depIdxs = []int32{
	2, // 0: apis.v1.ApiErrorResponse.error:type_name -> apis.v1.ApiError
	0, // 1: apis.v1.ApiError.code:type_name -> apis.v1.ErrorCode
	3, // 2: apis.v1.ApiError.details:type_name -> google.protobuf.Struct
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_apis_v1_errors_proto_init() }
func file_apis_v1_errors_proto_init() {
	if File_apis_v1_errors_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apis_v1_errors_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_v1_errors_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apis_v1_errors_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apis_v1_errors_proto_goTypes,
		DependencyIndexes: file_apis_v1_errors_proto_depIdxs,
		EnumInfos:         file_apis_v1_errors_proto_enumTypes,
		MessageInfos:      file_apis_v1_errors_proto_msgTypes,
	}.Build()
	File_apis_v1_errors_proto = out.File
	file_apis_v1_errors_proto_rawDesc = nil
	file_apis_v1_errors_proto_goTypes = nil
	file_apis_v1_errors_proto_depIdxs = nil
}
